version: "3.8"
services:
  app:
    build: .
    volumes:
      - ./main.py:/app/main.py
      - ./db.py:/app/db.py
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
    command: poetry run python main.py

